### ISSUE TITLE
elasticsearch.local=true does not work

### ISSUE THREAD

**Issue by vbuzzano** [feliperazeek/playframework-elasticsearch#1]
I set elasticsearch.local to true
elasticsearch.local = true

and i get the error: Configuration required - elasticsearch.client when local model is disabled!

In ElasticSearchPlugin.java at line 54, you use:
Boolean.getBoolean(Play.configuration.getProperty("elasticsearch.local").trim());

you should use:
Bolean.valueOf(Play.configuration.getProperty("elasticsearch.local").trim());

**Comment by feliperazeek** [comment]
Release 0.0.4 with Bug Fixes

Doc: https://github.com/feliperazeek/playframework-elasticsearch
Sample App: https://github.com/mashup-fm/playframework-elasticsearch-basicdemo
Step by Step Tutorial: http://geeks.aretotally.in/seven-steps-to-crud-with-play-framework-and-elastic-search-with-new-release-0-0-4

Thank you so much my friend!
Felipe
