### ISSUE TITLE
Model casting exception

### ISSUE THREAD

**Issue by vbuzzano** [feliperazeek/playframework-elasticsearch#2]
in the source ElasticSearchPlugin

you import the class and try to cast with
import play.db.jpa.Model;

instead of the interface 
import play.db.Model

**Comment by feliperazeek** [comment]
Lemme check why I am not getting these errors, I bet I have some .class somewhere.

**Comment by vbuzzano** [comment]
I use a class extending directly the class GenericModel instead of Model

**Comment by feliperazeek** [comment]
Release 0.0.4 with Bug Fixes

Doc: https://github.com/feliperazeek/playframework-elasticsearch
Sample App: https://github.com/mashup-fm/playframework-elasticsearch-basicdemo
Step by Step Tutorial: http://geeks.aretotally.in/seven-steps-to-crud-with-play-framework-and-elastic-search-with-new-release-0-0-4

Thank you so much my friend!
Felipe
