### ISSUE TITLE
ReflectionUtil.getFieldValue field not found

### ISSUE THREAD

**Issue by vbuzzano** [feliperazeek/playframework-elasticsearch#3]
in the method getFieldValue of class ReflectionUtil, you don't search for declared field in parent class ? .. may be it should be like that ?

```
public static Object getFieldValue(Object object, String fieldName) {
    try {
        Class<?> clazz = object.getClass();

        // Get all the fields including superclasses
        while (clazz != null) {
            for(Field field: clazz.getDeclaredFields())
                if (field.getName().equals(fieldName)) {
                    field.setAccessible(true);
                    return field.get(object);
                }
            clazz = clazz.getSuperclass();
        }
    } catch (Exception e) {
        Logger.warn(ExceptionUtil.getStackTrace(e));
        // throw new RuntimeException( e );
    }
    return null;
}
```

**Comment by feliperazeek** [comment]
Release 0.0.4 with Bug Fixes

Doc: https://github.com/feliperazeek/playframework-elasticsearch
Sample App: https://github.com/mashup-fm/playframework-elasticsearch-basicdemo
Step by Step Tutorial: http://geeks.aretotally.in/seven-steps-to-crud-with-play-framework-and-elastic-search-with-new-release-0-0-4

Thank you so much my friend!
Felipe
