### ISSUE TITLE
Use mappers in non-JPA Transformer

### ISSUE THREAD

**Issue by bgooren** [feliperazeek/playframework-elasticsearch#32]
The non-JPA Transformer does not use the mappers, which means custom field mappings will lead to errors.

**Comment by feliperazeek** [comment]
Is it easy to come up with a test to reproduce the problem?

**Comment by bgooren** [comment]
It's not a problem for us, since we always use hydration (and thus the JPATransformer).
I created this ticket as a reminder that this need to be fixed at some point.
Users will get errors if they do not use hydration and use custom field mappings.
