### ISSUE TITLE
Feature Request: Queue Support

### ISSUE THREAD

**Issue by yoko-** [feliperazeek/playframework-elasticsearch#4]
Would it be possible for this module to create a queue item for the JPA events instead of an ES call. And then a Queue client that will eventually pull and push the data into ES?

**Comment by feliperazeek** [comment]
Yea there's a discussion going on right now with the developers from Elastic Search to figure out what the best way to integrate is. One of the ideas is a queue solution, AMQP or JMS. What do you run? AMQP or JMS? And which server? Just wondering...

**Comment by yoko-** [comment]
I am still learning Play and checking if its a good contender for my next project. But on my other projects I have used Apache ActiveMQ (JMS). 

One more question regarding your ES module; how do I turn off _source?

**Comment by feliperazeek** [comment]
Play! is a great framework, the best one in Java in my opinion. I have been a Java developer for about 10 or 12 years so I have enough experience to compare. It has been such a joy since I started using it, I wish I was using in all my projects (sometimes I can't control it). 

You want to remove _source from the query results?

**Comment by yoko-** [comment]
I feel its a good framework as well. Just checking to see how mature it is.

Yes I want to remove _source from both the query result as well as prevent ES from storing it. I heard Shay say its optional.

**Comment by feliperazeek** [comment]
Hi Yoko just to let you know I am working on your request for queue integration in the elastic search module. I chose RabbitMQ instead of JMS, I wrote the RabbitMQ module. Did you see it?

I already wrote 75% of the code so you will hear from me soon. Does that sound good?

Thank you,
Felipe
