### ISSUE TITLE
Support for latest versions of ES

### ISSUE THREAD

**Issue by mardo** [feliperazeek/playframework-elasticsearch#44]
Today i tried to connect to an instance of ES version: 0.18.7
It was giving me the next warn:

15:45:25,861 WARN  ~ [Rigellian Recorder] Message not fully read (response) for [1] handler org.elasticsearch.client.transport.TransportClientNodesService$SniffNodesSampler$1$1@3bd37f3b, error [false], resetting

And wasn't indexing.
My conf:
%mdelcid.elasticsearch.local=false
%mdelcid.elasticsearch.client=localhost:9300

I did NOT use 9200, because was never connecting, never passed after the message:
INFO  ~ Transport Client - Host: localhost Port: 9300

So i used port 9300 instead (maybe i'm doing something wrong here)
Any way, i tested the same configuration with ES version 0.17.6 and all is working well (even with the 9300 port)

**Comment by bgooren** [comment]
The latest version of the elasticsearch module uses ES 0.18.5 (see #39, commit f53e89e); Let me check with Felipe if we can rollout a new release

**Comment by mardo** [comment]
Understood
