### ISSUE TITLE
ThreadLocal Client not right

### ISSUE THREAD

**Issue by eamelink** [feliperazeek/playframework-elasticsearch#6]
The Play Framework elasticsearch module version 0.0.5 contains a bug. It creates a ThreadLocal Client in ElasticSearchPlugin.java, but only for the thread that initializes the plugin.

So in DEV mode, with play.pool = 1 (default setting), everything works fine, as there is only a single thread.
In DEV mode with play.pool > 1, it breaks, because some requests are handled by different threads that have no ThreadLocal client, so there's a nullpointer error on ElasticSearch.java line 71

In PROD mode, play always has different threads for initialization and the requests, so it always breaks.

**Comment by feliperazeek** [comment]
I will check it out, thank you.

**Comment by eamelink** [comment]
Thanks :)

**Comment by feliperazeek** [comment]
It's fixed, pushing 0.0.6 out now with the fix. Thank you! I am trying to find more time to do everything I want to do on the module but it's been difficult the past couple of weeks. Super busy finishing some consulting jobs and doing job search. I will do a blog post with a sample app. Have a great one! Felipe

ps: by the way you can email me at felipera@gmail.com at anytime.
