### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by isamaru** [feliperazeek/playframework-elasticsearch#65]
I am trying to come up with some additions and I am reviewing the current architecture of  ElasticSearchPlugin. It seems to me that as it is, the class is not sufficiently thread-safe.
I prepared a simple fix in which I replaced all static collections with their Concurrent counterparts. This seems to reduce the risk of some thread shenanigans, but it will also slow us down a bit.
What do you think about this?

**Comment by feliperazeek** [comment]
Could you issue a pull request please?
